
var Constant = {
    CRYSTAL_WIDTH: 56,
    CRYSTAL_TYPE_COUNT: 6,
    CRYSTAL_META: 100,
    CRYSTAL_STONE: 200,

    CELL_WIDTH: 100,
    CELL_SPACE: 75,
    CELL_HEIGHT: 87,

    MAP_COLS: 9,
    MAP_ROWS: 8,
    MAP_WIDTH: 700,
    MAP_HEIGHT: 696,

    FALL_ACCELERATION: 30
};